clusterName: zurich
baseIpPrefix: "10.1.1"              # will become 10.10.X
dnsSuffix: "zurich.3gppnetwork.org"       # endpoint-cluster1-X.3gppnetwork.org
count: 100                         # how many endpoints to generate